### ISSUE TITLE
It does't  work inside AWS Nodejs lambda

### ISSUE THREAD

**Issue by mkovel** [serdnam/pino-cloudwatch-transport#3]
Hi, we spent tons of time to make it work inside AWS lambda. 
But with out success.  

Can you jump into this case ?
AWS lambda Nodejs 14

**Comment by tushar32** [comment]
Did the issue resolve?

**Comment by JeremieDemarchez** [comment]
No. With NodeJS 18, I get this error in the lambda log (not the expected log group) : 
2025-02-13T16:37:50.392Z	a245f93a-c43b-4b0a-943e-d3812dfe8e28	ERROR	Invoke Error 	
{
    "errorType": "Error",
    "errorMessage": "unable to determine transport target for \"@serdnam/pino-cloudwatch-transport\"",
    "stack": [
        "Error: unable to determine transport target for \"@serdnam/pino-cloudwatch-transport\"",
        "    at fixTarget (/node_modules/pino/lib/transport.js:160:13)",
        "    at Function.transport (/node_modules/pino/lib/transport.js:130:22)",
        "    at _Logger (/src/logger.ts:26:28)",
        "    at Runtime.handler (/src/lambda/handler.ts:17:18)",
        "    at Runtime.handleOnceNonStreaming (file:///var/runtime/index.mjs:1173:29)"
    ]
}

**Comment by serdnam** [comment]
Please leave a reproduction if possible so that I can look into this if I have time.
